# (Required) App Identifier
identifier = "io.robopipe.camera_api"
app_version = "0.5.32"
# (Required) App Entrypoint
entrypoint = ["bash", "-c", "cd /app && python3 -m robopipe_api"]

# (Optional) Prepare container commands
# Here is the place where you can install all the dependencies that are needed at run-time
prepare_container = [
    { type = "COPY", source = "requirements.txt", target = "requirements.txt" },
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3-pip git ffmpeg libsm6 libxext6" },
    { type = "RUN", command = "pip3 install -r /app/requirements.txt --break-system-packages" },
]

required_mounts = ["/data/robopipe:/app/data:rw,rbind"]

[env]
CORS_ORIGIN = "*"
PORT = "8080"
ROBOPIPE_DATA_DIR = "/app/data"
ROBOPIPE_RECORDING_ENABLED = "true"
ROBOPIPE_RECORDING_MAX_DURATION_SECONDS = "600"
